name: Run tests

on:
  push:
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache npm cache
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-cache-${{ hashFiles('baby-gru/package-lock.json') }}
        restore-keys: |
          npm-cache-

    - name: Install dependencies
      working-directory: baby-gru
      run: npm ci

    - name: Test typescript transpilation
      working-directory: baby-gru
      run: |
        npm run create-version
        npm run transpile-protobuf
        npx graphql-codegen
        npx tsc
        
    - name: Run react tests
      working-directory: baby-gru
      run: npm run test-react
